export const CUSTOM_DRAWER = [
  {
    id: 1,
    // name: 'NEWS',
    name: 'LOGIN',

    iconName: 'hashtag',
    iconType: 'FontAwesome5',
    iconColor: 'black',
    route: 'Login',
  },
  {
    id: 2,
    // name: 'CHANNEL',
    name: 'OnBoarding',

    iconName: 'view-comfortable',
    iconType: 'MaterialIcons',
    iconColor: 'black',
    route: 'OnBoarding',
  },
  {
    id: 3,
    name: 'OVERVIEW',
    iconName: 'stats-chart',
    iconType: 'Ionicons',
    iconColor: 'black',
    route: 'Notifications',
  },
  {
    id: 4,
    name: 'CALENDER',
    iconName: 'calendar',
    iconType: 'AntDesign',
    iconColor: 'black',
    route: 'Notifications',
  },
  {
    id: 5,
    name: 'TIMELINE',
    iconName: 'clock-time-ten-outline',
    iconType: 'MaterialCommunityIcons',
    iconColor: 'black',
    route: 'Notifications',
  },
  {
    id: 6,
    name: 'PROFILE',
    iconName: 'user',
    iconType: 'FontAwesome',
    iconColor: 'black',
    route: 'Notifications',
  },
  {
    id: 7,
    name: 'SETTING',
    iconName: 'md-settings',
    iconType: 'Ionicons',
    iconColor: 'black',
    route: 'Notifications',
  },
  {
    id: 8,
    name: 'FEEDBACK',
    iconName: 'file',
    iconType: 'Octicons',
    iconColor: 'black',
    route: 'Notifications',
  },
];
